[package]
name = "manhwa18cc"
version = "0.1.7"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
tanoshi-lib = "0.27.0"
madara = { path = "../../common/madara" }
anyhow = "1"
scraper = "0.13"
ureq = { version = "2", features = ["json"] }
