[package]
name = "manganato"
version = "0.1.2"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
tanoshi-lib = "0.27.0"
mangakakalot-common = { path = "../../common/mangakakalot" }
anyhow = "1"
ureq = { version = "2", features = ["json"] }
